<a href="https://colab.research.google.com/github/pavanreddy565/PyTorch_learning/blob/main/basics/pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Basics: Tensors & Gradients**

In [ ]:
import torch

# **Tensors**
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [ ]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
#vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
#matrix
t3 =torch.tensor([[5,6],[7,8],[9,10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
# 3-dimesional array
t4=torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

Tensors can have any number of dimesions, and different lenths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor

In [ ]:
t1.shape,t2.shape,t3.shape,t4.shape

(torch.Size([]), torch.Size([4]), torch.Size([3, 2]), torch.Size([2, 2, 3]))

# **Tensor Operations and gradients**
We can combine tensors with the usaul arithemetic operations. Let's look an example

In [ ]:
# create tensors
x = torch.tensor(3.)
y = torch.tensor(4., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

In [ ]:
w = y * x + z
w

tensor(17., grad_fn=<AddBackward0>)

as expected, ``` w ``` is a tensor with the value ``` 3 * 4 + 5 =17 ``` . what makes PyTorch special is that we can automatically compute the derivative of ```w ``` w.r.t  the tensors that have ``` requires_grad=True ``` i.e ```y``` and ```z ``` . To compute the derivatives, we can call the ```.backward``` method on our result ```w```.


In [ ]:
# computive derivatives
w.backward()

the deivatives of ```w ``` w.r.t the input tensors are stored in the ```.grad``` property of the respective tensors.

In [ ]:
# Display Gradients
print(f'dw/dx : {x.grad}')
print(f'dw/dy : {y.grad}')
print(f'dw/dz : {z.grad}')

dw/dx : None
dw/dy : 3.0
dw/dz : 1.0


As expected, dw/dy has the same value as x i.e. 3, and dw/dz has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.

The "grad" in y.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

# **Interoperability with Numpy**
Numpy is a popular open source library used for mathematical and scientific computing in Python. it enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of suppourting libraries


*   Matplotlib for ploting and visulazation
*   OpenCV for image and video processing
*   pandas for file I/O and data anyalsis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage it existing ecosystem of tools and libraries




In [ ]:
import numpy as np

x=np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# convert the numpy array to a torch tensor
y = torch.from_numpy(x) # it uses same space in the memory

b = torch.tensor(x)# it creates a space in the memory

y,b

(tensor([[1., 2.],
         [3., 4.]], dtype=torch.float64),
 tensor([[1., 2.],
         [3., 4.]], dtype=torch.float64))

In [ ]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [ ]:
# convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interperability between PyTorch and Numpy is really important because most datasets most datasets you'll work with likely be read and preprocessed as Numpy arrays.

pytorch tensors and numpy arrays works in simalar manner but pytorch tensors are mostly likely designed for the GPU's(parrallel computing).pytorch tensors are written in cuda which is used to intract with nvidia's GPU


pytorch documentation :- https://pytorch.org/docs/stable/tensors.html